const events = [
  {
    date: "2026-04-17",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 17. April - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    status: "Vergangen"
  },
  {
    date: "2026-05-08",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 08. Mai - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    status: "Findet statt"
  },
  {
    date: "2026-06-12",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 12. Juni - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    status: "Findet statt"
  },
  {
    date: "2026-07-10",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 10. Juli - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    status: "Wetterabhängig"
  },
  {
    date: "2026-08-14",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 14. August - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    status: "Findet statt"
  },
  {
    date: "2026-09-18",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 18. September - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    status: "Findet statt"
  },
  {
    date: "2026-10-09",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 09. Oktober - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    status: "Findet statt"
  }
];
