/* ==========================================
   events-data.js
   ========================================== */

const events = [
  {
    date: "2026-04-17",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 17. April - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    isCancelled: false,
    cancelNote: ""
  },
  {
    date: "2026-05-08",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 08. Mai - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    isCancelled: false,
    cancelNote: ""
  },
  {
    date: "2026-06-12",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 12. Juni - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    isCancelled: true,
    cancelNote: "Heute nur kurzes Stehbier ab 18 Uhr aufgrund des Wetters"
  },
  {
    date: "2026-07-10",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 10. Juli - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    isCancelled: false,
    cancelNote: ""
  },
  {
    date: "2026-08-14",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 14. August - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    isCancelled: false,
    cancelNote: ""
  },
  {
    date: "2026-09-18",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 18. September - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    isCancelled: false,
    cancelNote: ""
  },
  {
    date: "2026-10-09",
    startTime: "18:00",
    endTime: "22:00",
    title: "Auf ein Bier... mit dem Galgenberg",
    fullTitle: "Freitag, 09. Oktober - 18 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Prof.-Wagner-Platz",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    isCancelled: false,
    cancelNote: ""
  },
   {
  date: "2026-08-07",
  startTime: "18:00",
  endTime: "23:59",
  title: "Galgenberg-Festival 2026",
  fullTitle: "Freitag, 7. August - 18 Uhr - Galgenberg-Festival 2026",
  shortText: "25. Ausgabe des Galgenberg-Festivals auf dem Gelände des ehemaligen Gaskessel-Areals.",
  image: "galgenberg-festival-2026.png",
  contact: "Kulturfreunde Galgenberg e. V.",
  location: "Hirschbachstraße 14, 73431 Aalen",
  description: "Galgenberg-Festival 2026 auf dem Gelände des ehemaligen Gaskessel-Areals.",
  hint: "Weitere Infos und Programm: https://www.galgenberg-festival.de/",
  isCancelled: false,
  cancelNote: ""
},
{
  date: "2026-08-08",
  startTime: "19:30",
  endTime: "23:59",
  title: "Galgenberg-Festival 2026",
  fullTitle: "Samstag, 8. August - 19:30 Uhr - Galgenberg-Festival 2026",
  shortText: "Live-Musik-Nacht beim Galgenberg-Festival 2026.",
  image: "galgenberg-festival-2026.png",
  contact: "Kulturfreunde Galgenberg e. V.",
  location: "Hirschbachstraße 14, 73431 Aalen",
  description: "Live-Musik-Nacht im Rahmen des Galgenberg-Festivals 2026.",
  hint: "Weitere Infos und Programm: https://www.galgenberg-festival.de/festival-2026/",
  isCancelled: false,
  cancelNote: ""
},
{
  date: "2026-09-11",
  startTime: "10:00",
  endTime: "23:00",
  title: "Reichsstädter Tage 2026",
  fullTitle: "Freitag, 11. September - Reichsstädter Tage 2026",
  shortText: "Stadtfest in der Aalener Innenstadt.",
  image: "reichsstaedter-tage-2026.png",
  contact: "Stadt Aalen",
  location: "Innenstadt Aalen",
  description: "Reichsstädter Tage 2026 in der Aalener Innenstadt.",
  hint: "Offizielle Infos: https://www.aalen.de/reichsstaedter-tage-2026.238088.htm",
  isCancelled: false,
  cancelNote: ""
},
{
  date: "2026-09-12",
  startTime: "10:00",
  endTime: "23:00",
  title: "Reichsstädter Tage 2026",
  fullTitle: "Samstag, 12. September - Reichsstädter Tage 2026",
  shortText: "Stadtfest in der Aalener Innenstadt.",
  image: "reichsstaedter-tage-2026.png",
  contact: "Stadt Aalen",
  location: "Innenstadt Aalen",
  description: "Reichsstädter Tage 2026 in der Aalener Innenstadt.",
  hint: "Offizielle Infos: https://www.aalen.de/reichsstaedter-tage-2026.238088.htm",
  isCancelled: false,
  cancelNote: ""
},
{
  date: "2026-09-13",
  startTime: "10:00",
  endTime: "18:00",
  title: "Reichsstädter Tage 2026",
  fullTitle: "Sonntag, 13. September - Reichsstädter Tage 2026",
  shortText: "Stadtfest in der Aalener Innenstadt.",
  image: "reichsstaedter-tage-2026.png",
  contact: "Stadt Aalen",
  location: "Innenstadt Aalen",
  description: "Reichsstädter Tage 2026 in der Aalener Innenstadt.",
  hint: "Offizielle Infos: https://www.aalen.de/reichsstaedter-tage-2026.238088.htm",
  isCancelled: false,
  cancelNote: ""
},
];
