const events = [
  {
    date: "2026-04-17",
    startTime: "19:00",
    endTime: "21:00",
    title: "Auf ein Bier mit dem Galgenberg",
    fullTitle: "Freitag, 17. April - 19 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Nachbarschaftstreffen für Gespräche, Kennenlernen und Austausch im Viertel.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Treffpunkt im Viertel / Galgenberg",
    description: "Offenes Nachbarschaftstreffen zum Kennenlernen und Austauschen.",
    hint: "Für alle offen.",
    status: "Vergangen"
  },
  {
    date: "2026-05-08",
    startTime: "19:00",
    endTime: "21:00",
    title: "Auf ein Bier mit dem Galgenberg",
    fullTitle: "Freitag, 08. Mai - 19 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Ein offenes Nachbarschaftstreffen für Gespräche, Kennenlernen und Austausch im Viertel.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Treffpunkt im Viertel / Galgenberg",
    description: "Gemeinsames Treffen für Gespräche, neue Ideen und lockeren Austausch.",
    hint: "Bitte gern Nachbarn mitbringen.",
    status: "Findet statt"
  },
  {
    date: "2026-06-12",
    startTime: "19:00",
    endTime: "21:00",
    title: "Auf ein Bier mit dem Galgenberg",
    fullTitle: "Freitag, 12. Juni - 19 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Nachbarschaftliches Beisammensein mit Raum für neue Vorschläge und Gespräche.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Treffpunkt im Viertel / Galgenberg",
    description: "Nachbarschaftliches Beisammensein mit Raum für neue Vorschläge und Gespräche.",
    hint: "Für alle offen.",
    status: "Findet statt"
  },
  {
    date: "2026-07-10",
    startTime: "19:00",
    endTime: "21:00",
    title: "Auf ein Bier mit dem Galgenberg",
    fullTitle: "Freitag, 10. Juli - 19 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Sommerliches Treffen im Viertel mit lockerem Austausch.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Treffpunkt im Viertel / Galgenberg",
    description: "Sommerliches Treffen im Viertel mit lockerem Austausch.",
    hint: "Nur bei sehr schlechtem Wetter ggf. kurzfristige Änderung.",
    status: "Wetterabhängig"
  },
  {
    date: "2026-08-14",
    startTime: "19:00",
    endTime: "21:00",
    title: "Auf ein Bier mit dem Galgenberg",
    fullTitle: "Freitag, 14. August - 19 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Offenes Treffen für Nachbarn mit Ideen, Fragen oder einfach Lust auf Austausch.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Treffpunkt im Viertel / Galgenberg",
    description: "Offenes Treffen für Nachbarn mit Ideen, Fragen oder einfach Lust auf Austausch.",
    hint: "Neue Gesichter willkommen.",
    status: "Findet statt"
  },
  {
    date: "2026-09-18",
    startTime: "19:00",
    endTime: "21:00",
    title: "Auf ein Bier mit dem Galgenberg",
    fullTitle: "Freitag, 18. September - 19 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Gemeinsames Treffen zur Vernetzung und für Themen aus der Nachbarschaft.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Treffpunkt im Viertel / Galgenberg",
    description: "Gemeinsames Treffen zur Vernetzung und für Themen aus der Nachbarschaft.",
    hint: "Für alle offen.",
    status: "Findet statt"
  },
  {
    date: "2026-10-09",
    startTime: "19:00",
    endTime: "21:00",
    title: "Auf ein Bier mit dem Galgenberg",
    fullTitle: "Freitag, 09. Oktober - 19 Uhr - Auf ein Bier mit dem Galgenberg",
    shortText: "Herbstliches Nachbarschaftstreffen mit Gesprächen und Ideen fürs Viertel.",
    image: "event2.png",
    contact: "Renate, Angela, Thomas, Johannes",
    location: "Treffpunkt im Viertel / Galgenberg",
    description: "Herbstliches Nachbarschaftstreffen mit Gesprächen und Ideen fürs Viertel.",
    hint: "Bitte warm anziehen, wenn wir draußen stehen.",
    status: "Findet statt"
  }
];
